apiVersion: v1
kind: Service
metadata:
  labels:
    app: insurance
  name: insurance
spec:
  type: NodePort
  ports:
    - name: "insurance-service"
      port: 5000
      targetPort: 8080
  selector:
    app: insurance
